### ISSUE TITLE
Too many slashes in file URI file:////

### ISSUE THREAD

**Issue by opiethehokie** [cloudfoundry/buildpack-packager#10]
I think the `sub("file:", "file://")` in [this change](https://github.com/cloudfoundry/buildpack-packager/commit/7c01e9f595ba08c37acce178cf1b1d5873ffedff#diff-eb0f321eb543a80e1604a2f0371e2638R81) may not be needed. Unless I'm doing something wrong in my manifest.yml where I have a file URI like `file://filename`, it's changing it to `file:////filename`.

The cached file ends up with extra underscores in the name and then when the the buildpack is executing the compile-extensions download_dependency script can't find it in the cache.

**Comment by sesmith177** [comment]
Hello @opiethehokie, 

The format for a file URI is `file://localhost/path` or, as a shortcut, `file:///path`. Note the *triple* slash.

It's confusing because the file URI format is trying to fit the general URI format, including hostnames.

We can't change the URI format, so unfortunately closing this issue.
